name: ChatGPT Agent - Build Plugin
on:
  issues:
    types: [opened, edited]
  issue_comment:
    types: [created]
permissions:
  contents: write
  pull-requests: write
  issues: write

jobs:
  generate:
    if: |
      (github.event_name == 'issues') ||
      (github.event_name == 'issue_comment' && startsWith(github.event.comment.body, '/agent'))
    runs-on: ubuntu-latest
    env:
      OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v4

           - name: Determine request text
        id: req
        shell: bash
        run: |
          if [[ "${{ github.event_name }}" == "issues" ]]; then
            {
              printf 'text<<EOF\n'
              printf '%s — %s\n' "${{ github.event.issue.title }}" "${{ github.event.issue.body }}"
              printf 'EOF\n'
            } >> "$GITHUB_OUTPUT"
          else
            echo "text=${{ github.event.comment.body }}" >> "$GITHUB_OUTPUT"
          fi


      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 22

      - name: Install deps for agent script
        run: |
          npm init -y --scope agent >/dev/null 2>&1
          npm i openai@^4 @octokit/rest@^20

      - name: Run agent (plan -> files -> branch -> PR)
        id: agent
        run: |
          node .github/agent/plan-and-commit.mjs <<'EOF'
          ${{ steps.req.outputs.text }}
          EOF

      - name: Post PR link
        if: steps.agent.outputs.pr_url != ''
        uses: actions/github-script@v7
        with:
          script: |
            const url = "${{ steps.agent.outputs.pr_url }}";
            const issue_number = context.payload.issue?.number || context.payload.comment?.issue_url.split('/').pop();
            await github.rest.issues.createComment({ ...context.repo, issue_number, body: `✅ Agent opened PR: ${url}` });
