name: PR Pretty URL Cleanup

on:
  pull_request:
    types: [closed]

jobs:
  delete-dns:
    runs-on: ubuntu-latest
    steps:
      - name: Delete CNAME in Cloudflare
        env:
          CF_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          ZONE: ${{ secrets.CLOUDFLARE_ZONE_ID }}
          FQDN: pr-${{ github.event.number }}.stage.sniffrpack.com
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          rec_id=$(curl -s -X GET "https://api.cloudflare.com/client/v4/zones/$ZONE/dns_records?type=CNAME&name=$FQDN" \
            -H "Authorization: Bearer $CF_TOKEN" -H "Content-Type: application/json" | jq -r '.result[0].id')
          if [ "$rec_id" != "null" ] && [ -n "$rec_id" ]; then
            curl -s -X DELETE "https://api.cloudflare.com/client/v4/zones/$ZONE/dns_records/$rec_id" \
              -H "Authorization: Bearer $CF_TOKEN" -H "Content-Type: application/json" >/dev/null
            echo "Deleted $FQDN"
          else
            echo "No record to delete for $FQDN"
          fi
