name: Preview (Web)

on:
  pull_request:
    types: [opened, synchronize, reopened]
  pull_request_target:
    types: [closed]

jobs:
  upsert:
    if: github.event_name == 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install deps
        run: |
          sudo apt-get update && sudo apt-get install -y jq
          corepack enable
      - name: Get Render PR preview URL (web)
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_WEB_SERVICE_ID }}
          BRANCH: ${{ github.head_ref }}
        run: |
          node ./scripts/render-get-preview-url.mjs web > web_url.txt
          echo "WEB_RENDER_URL=$(cat web_url.txt)" >> $GITHUB_ENV
      - name: Get Render PR preview URL (api)
        env:
          RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
          SERVICE_ID: ${{ secrets.RENDER_API_SERVICE_ID }}
          BRANCH: ${{ github.head_ref }}
        run: |
          node ./scripts/render-get-preview-url.mjs api > api_url.txt
          echo "API_RENDER_URL=$(cat api_url.txt)" >> $GITHUB_ENV
      - name: Upsert pretty URL mapping
        env:
          PR_NUM: ${{ github.event.pull_request.number }}
          WORKER_WEBHOOK: ${{ secrets.PREVIEW_WORKER_URL }}
          WORKER_SECRET: ${{ secrets.PREVIEW_WORKER_SECRET }}
        run: |
          curl -fsSL -X POST "$WORKER_WEBHOOK" \
            -H "x-webhook-secret: $WORKER_SECRET" \
            -H 'content-type: application/json' \
            --data "{\"action\":\"upsert\",\"pr\":$PR_NUM,\"api\":\"$API_RENDER_URL\",\"web\":\"$WEB_RENDER_URL\"}"

  cleanup:
    if: github.event.pull_request.merged == true || github.event.action == 'closed'
    runs-on: ubuntu-latest
    steps:
      - name: Delete mapping on close
        env:
          PR_NUM: ${{ github.event.pull_request.number }}
          WORKER_WEBHOOK: ${{ secrets.PREVIEW_WORKER_URL }}
          WORKER_SECRET: ${{ secrets.PREVIEW_WORKER_SECRET }}
        run: |
          curl -fsSL -X POST "$WORKER_WEBHOOK" \
            -H "x-webhook-secret: $WORKER_SECRET" \
            -H 'content-type: application/json' \
            --data "{\"action\":\"delete\",\"pr\":$PR_NUM}"
