name: Runner Image

on:
  workflow_dispatch:
  push:
    branches: [ main ]
    paths:
      - tools/runner/Dockerfile

jobs:
  build-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push
        uses: docker/build-push-action@v6
        with:
          file: tools/runner/Dockerfile
          context: .
          push: true
          tags: ghcr.io/${{ github.repository }}/snf-runner:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
